ifeq (,$(filter netdev_whitefield,$(USEMODULE)))
ifneq (,$(filter netdev_default gnrc_netdev_default,$(USEMODULE)))
    USEMODULE += netdev_tap
endif
endif

ifneq (,$(filter mtd,$(USEMODULE)))
    USEMODULE += mtd_native
endif

ifneq (,$(filter can,$(USEMODULE)))
    ifeq ($(shell uname -s),Linux)
        USEMODULE += can_linux
        CFLAGS += -DCAN_DLL_NUMOF=2
    endif
endif
